language: node_js
node_js:
  - 5.0.0
before_install:
  - npm install -g phantomjs
before_script:
  - npm run init
script:
  - phantomjs test/run-qunit.js demo/testSurfaceUtil.html
  - phantomjs test/run-qunit.js demo/testSurfaceRender.html
  - phantomjs test/run-qunit.js demo/testSurface.html
  - phantomjs test/run-qunit.js demo/testShell.html
after_script:
after_succses:
after_failure:
notifications:
  emails:
 on_success: change
 on_failure: change
