language: node_js
node_js:
  - 5.0.0
branches:
  only: 'master'
before_install:
  - npm install -g dtsm browserify bower
before_script:
  - npm run init
script:
  - phantomjs test/run-qunit.js demo/testSurfaceUtil.html
  - phantomjs test/run-qunit.js demo/testSurfaceRender.html
  - phantomjs test/run-qunit.js demo/testSurface.html
  - phantomjs test/run-qunit.js demo/testShell.html
#after_script:
#after_succses:
#after_failure:
