language: node_js
node_js:
  - 6.3.1
branches:
  only: 5.x
before_install: null
before_script: null
script:
  - echo "nothing"
after_script:
  - set -e
  - mkdir gh-pages
  - mv dist demo nar bower.json ./gh-pages
  - cd gh-pages
  - git init
  - git checkout -b gh-pages
  - npm install -g bower
  - bower install
  - git status
  - git add -f dist demo nar bower_components
  - git commit -am "travis-auto-update"
  - git status
  - git ls-files
  - >-
    [ "$TRAVIS_BRANCH" == "5.x" ] && [ $GH_TOKEN ] && git push --force --quiet
    "https://${GH_TOKEN}@github.com/Ikagaka/Shell.js.git" gh-pages:gh-pages >
    /dev/null 2>&1
  - cd ..
  - 'git clone https://github.com/Ikagaka/cuttlebone.git'
  - cd cuttlebone
  - git checkout dev
  - ls -la
  - npm run setup
  - npm run init
  - git status
  - git commit -am "travis-auto-update"
  - git status
  - git ls-files
  - >-
    [ "$TRAVIS_BRANCH" == "5.x" ] && [ $GH_TOKEN ] && git push --quiet
    "https://${GH_TOKEN}@github.com/Ikagaka/cuttlebone.git" dev:dev > /dev/null
    2>&1
env:
  global:
    - GIT_COMMITTER_NAME=legokichi
    - GIT_COMMITTER_EMAIL=legokichi@gmail.com
    - GIT_AUTHOR_NAME=legokichi
    - GIT_AUTHOR_EMAIL=legokichi@gmail.com
    - secure: >-
        jLy2F4sZHXwCz1NSZEf8VaihXTwbi8M35TJD9v+yXlSn/jAwejA5gZNcv4NetdAb2ifKRQTpVmJPHOCdm0wcYhAOmyJpluqgKGWfEfEFjufT421ZSLshgUcUHFjdKoNKh5C2tHQhP344OXbE8VHrIO8WFaqNRyjB0CeuB7Eyqws=
