language: node_js
node_js:
  - 6.0.0
branches:
  only: '5.x'
before_install:
before_script:
script:
  - echo "nothing"
after_script:
  - git stash
  - npm install -g bower 
  - git fetch origin gh-pages
  - git checkout gh-pages
  - git checkout 5.x dist demo nar bower.json
  - bower install
  - git status
  - git add dist demo nar bower_components
  - git commit -am "travis-auto-update"
  - git status
  - git ls-files
  - '[ "$TRAVIS_BRANCH" == "5.x" ] && [ $GH_TOKEN ] && git push --force --quiet "https://${GH_TOKEN}@github.com/Ikagaka/Shell.git" gh-pages:gh-pages > /dev/null 2>&1'
env:
  global:
    - GIT_COMMITTER_NAME=legokichi
    - GIT_COMMITTER_EMAIL=legokichi@gmail.com
    - GIT_AUTHOR_NAME=legokichi
    - GIT_AUTHOR_EMAIL=legokichi@gmail.com
    - secure: "Qb4ImvPXMDvTX4tVQ16BxfaZZ8NUGWFsmwDT/Zgb4L2rWT8mPb4SXPe9wjazmzqW9AdxnQ4V1reuVfVhIxcu21nxzYDxnc1+IyJ4dhISRoi80994iOfhllfjztZLUDzRZBcyO475IEgpD+v2V5KzAbafpfoZRLgemIxFQmjvhOw="
