language: node_js
node_js:
  - 6.0.0
branches:
  only: '5.x'
before_install:
before_script:
  - npm run setup
  - npm run init
script:
  - echo "nothing"
after_script:
  - git fetch origin gh-pages
  - git checkout gh-pages
  - bower update
  - git status
  - git commit -am "travis-auto-update"
  - git ls-files
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --force --quiet "https://${GH_TOKEN}@github.com/Ikagaka/Shell.git" gh-pages:gh-pages > /dev/null 2>&1'
env:
  global:
    - GIT_COMMITTER_NAME=legokichi
    - GIT_COMMITTER_EMAIL=legokichi@gmail.com
    - GIT_AUTHOR_NAME=legokichi
    - GIT_AUTHOR_EMAIL=legokichi@gmail.com
    - secure: "Qb4ImvPXMDvTX4tVQ16BxfaZZ8NUGWFsmwDT/Zgb4L2rWT8mPb4SXPe9wjazmzqW9AdxnQ4V1reuVfVhIxcu21nxzYDxnc1+IyJ4dhISRoi80994iOfhllfjztZLUDzRZBcyO475IEgpD+v2V5KzAbafpfoZRLgemIxFQmjvhOw="
