// Generated by CoffeeScript 1.10.0
(function() {
  var Balloon, Blimp, Named, NamedManager, Scope, Shell, Surface, SurfaceRender, SurfaceUtil, ref, ref1;

  ref = require("ikagaka.shell.js"), Shell = ref.Shell, Surface = ref.Surface, SurfaceUtil = ref.SurfaceUtil, SurfaceRender = ref.SurfaceRender;

  ref1 = require("ikagaka.balloon.js"), Balloon = ref1.Balloon, Blimp = ref1.Blimp;

  NamedManager = require("./NamedManager");

  Named = require("./Named");

  Scope = require("./Scope");

  exports.Balloon = Balloon;

  exports.Blimp = Blimp;

  exports.Shell = Shell;

  exports.Surface = Surface;

  exports.SurfaceUtil = SurfaceUtil;

  exports.SurfaceRender = SurfaceRender;

  exports.NamedManager = NamedManager;

  exports.Named = Named;

  exports.Scope = Scope;

}).call(this);
