// Generated by CoffeeScript 1.10.0
(function() {
  var Named, NamedManager, Scope;

  NamedManager = require("./NamedManager");

  Named = require("./Named");

  Scope = require("./Scope");

  exports.NamedManager = NamedManager;

  exports.Named = Named;

  exports.Scope = Scope;

}).call(this);
