// Generated by CoffeeScript 1.10.0
(function() {
  var Named, Scope, SurfaceUtil,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  SurfaceUtil = require("ikagaka.shell.js").SurfaceUtil;

  Scope = require("./Scope").Scope;

  Named = (function(superClass) {
    extend(Named, superClass);

    function Named(namedId, shell, balloon, nmdmgr) {
      this.namedId = namedId;
      this.shell = shell;
      this.balloon = balloon;
      this.nmdmgr = nmdmgr;
      Named.__super__.constructor.call(this);
      this.element = document.createElement("div");
      this.scopes = [];
      this.currentScope = null;
      this.destructors = [];
      this.initDOMStructure();
      this.initEventListener();
      this.scope(0).surface(0);
      this.scope(1).surface(10);
      Promise.resolve(this);
    }

    Named.prototype.initDOMStructure = function() {
      this.$named = $(this.element).addClass("named");
    };

    Named.prototype.initEventListener = function() {
      var $target, relLeft, relTop;
      $target = null;
      relLeft = relTop = 0;
      this.shell.on("mouse", (function(_this) {
        return function(ev) {
          var $scope, left, pageX, pageY, ref, top;
          if (ev.transparency === true && ev.type !== "mousemove") {
            SurfaceUtil.recursiveElementFromPoint(ev.event, _this.nmdmgr.element, ev.event.target);
            return;
          }
          switch (ev.type) {
            case "mouseup":
              $target = null;
              break;
            case "mousemove":
              if ($target != null) {
                if (/^touch/.test(ev.event.type)) {
                  pageX = ev.event.touches[0].pageX;
                  pageY = ev.touches[0].pageY;
                } else {
                  pageX = ev.event.pageX;
                  pageY = ev.event.pageY;
                }
                $target.css({
                  left: pageX - relLeft,
                  top: pageY - relTop
                });
              }
              break;
            case "mousedown":
              $target = $scope = $(_this.scopes[ev.scopeId].element);
              ref = $target.offset(), top = ref.top, left = ref.left;
              if (/^touch/.test(ev.event.type)) {
                pageX = ev.event.touches[0].pageX;
                pageY = ev.event.touches[0].pageY;
              } else {
                pageX = ev.event.pageX;
                pageY = ev.event.pageY;
              }
              relLeft = pageX - left;
              relTop = pageY - top;
              _this.$named.append($scope);
              _this.$named.appendTo(_this.nmdmgr.element);
          }
        };
      })(this));
      this.balloon.on("mouse", (function(_this) {
        return function(ev) {
          var $scope;
          $scope = $(_this.scopes[ev.scopeId].element);
          switch (ev.type) {
            case "mousedown":
              _this.$named.append($scope);
              _this.$named.appendTo(_this.nmdmgr.element);
          }
        };
      })(this));
      this.balloon.on("select", (function(_this) {
        return function(ev) {
          console.log(ev);
          return _this.emit("select", ev);
        };
      })(this));
    };

    Named.prototype.destructor = function() {
      this.scopes.forEach(function(scope) {
        return scope.destructor();
      });
      this.scopes = [];
      this.destructors.forEach(function(fn) {
        return fn();
      });
      this.$named.children().remove();
      this.$named.remove();
    };

    Named.prototype.scope = function(scopeId) {
      if (scopeId == null) {
        return this.currentScope;
      }
      if (typeof scopeId !== "number") {
        console.warn("scopeId:", scopeId, "is not a number");
        return this.currentScope;
      }
      if (this.scopes[scopeId] == null) {
        this.scopes[scopeId] = new Scope(scopeId, this.shell, this.balloon, this);
      }
      this.currentScope = this.scopes[scopeId];
      this.$named.append(this.scopes[scopeId].element);
      return this.currentScope;
    };

    Named.prototype.openInputBox = function(id, text) {
      var event;
      if (text == null) {
        text = "";
      }
      event = {
        "type": "userinput",
        "id": id,
        "content": prompt("UserInput", text)
      };
      this.emit("input", event);
    };

    Named.prototype.openCommunicateBox = function(text) {
      var event;
      if (text == null) {
        text = "";
      }
      event = {
        "type": "communicateinput",
        "sender": "user",
        "content": prompt("Communicate", text)
      };
      this.emit("input", event);
    };

    return Named;

  })(EventEmitter2);

  exports.Named = Named;

}).call(this);
