// Generated by CoffeeScript 1.10.0
(function() {
  var Named, NamedManager,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Named = require("./Named").Named;

  NamedManager = (function(superClass) {
    extend(NamedManager, superClass);

    function NamedManager() {
      NamedManager.__super__.constructor.call(this);
      this.element = document.createElement("div");
      this.namedies = [];
      this.destructors = [];
      this.initDOMStructure();
      this.initStyle();
      this.initEventListener();
    }

    NamedManager.prototype.initDOMStructure = function() {
      this.$namedMgr = $(this.element).addClass("namedMgr");
    };

    NamedManager.prototype.initStyle = function() {
      var $style;
      $style = $("<style scoped />").text(".scope {\n  position: absolute;\n  pointer-events: none;\n  user-select: none;\n  -webkit-tap-highlight-color: transparent;\n}\n.surface {\n}\n.surfaceCanvas {\n  pointer-events: auto;\n}\n.blimp {\n  position: absolute;\n  top: 0px;\n  left: 0px;\n  pointer-events: auto;\n}").appendTo(this.$namedMgr);
    };

    NamedManager.prototype.initEventListener = function() {
      var onmousedown;
      onmousedown = (function(_this) {
        return function(ev) {
          return setTimeout((function() {
            return _this.$namedMgr.append(ev.currentTarget);
          }), 300);
        };
      })(this);
      this.$namedMgr.on("mousedown", ".named", onmousedown);
      this.$namedMgr.on("touchstart", ".named", onmousedown);
      this.destructors.push((function(_this) {
        return function() {
          _this.$namedMgr.off("mousedown", ".named", onmousedown);
          return _this.$namedMgr.off("touchstart", ".named", onmousedown);
        };
      })(this));
    };

    NamedManager.prototype.destructor = function() {
      this.namedies.forEach(function(named) {
        return named.destructor();
      });
      this.namedies = [];
      this.destructors.forEach(function(fn) {
        return fn();
      });
      this.$namedMgr.children().remove();
      this.$namedMgr.remove();
    };

    NamedManager.prototype.materialize = function(shell, balloon) {
      var named, namedId;
      namedId = this.namedies.length;
      named = new Named(namedId, shell, balloon, this);
      this.namedies.push(named);
      this.$namedMgr.append(named.element);
      return namedId;
    };

    NamedManager.prototype.vanish = function(namedId) {
      if (this.namedies[namedId] == null) {
        console.error("namedId " + namedId + " is not used yet");
      }
      this.namedies[namedId].destructor();
      this.namedies[namedId] = null;
      delete this.namedies[namedId];
    };

    NamedManager.prototype.named = function(namedId) {
      if (this.namedies[namedId] == null) {
        console.error("namedId " + namedId + " is not used yet");
        return null;
      }
      return this.namedies[namedId];
    };

    return NamedManager;

  })(EventEmitter2);

  exports.NamedManager = NamedManager;

}).call(this);
